/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZzIndexRouteImport } from './routes/zz/index'
import { Route as MeshcoreIndexRouteImport } from './routes/meshcore/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CzlanIndexRouteImport } from './routes/czlan/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZzIndexRoute = ZzIndexRouteImport.update({
  id: '/zz/',
  path: '/zz/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshcoreIndexRoute = MeshcoreIndexRouteImport.update({
  id: '/meshcore/',
  path: '/meshcore/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CzlanIndexRoute = CzlanIndexRouteImport.update({
  id: '/czlan/',
  path: '/czlan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/czlan/': typeof CzlanIndexRoute
  '/events/': typeof EventsIndexRoute
  '/meshcore/': typeof MeshcoreIndexRoute
  '/zz/': typeof ZzIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/czlan': typeof CzlanIndexRoute
  '/events': typeof EventsIndexRoute
  '/meshcore': typeof MeshcoreIndexRoute
  '/zz': typeof ZzIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/czlan/': typeof CzlanIndexRoute
  '/events/': typeof EventsIndexRoute
  '/meshcore/': typeof MeshcoreIndexRoute
  '/zz/': typeof ZzIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$productId'
    | '/czlan/'
    | '/events/'
    | '/meshcore/'
    | '/zz/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/$productId' | '/czlan' | '/events' | '/meshcore' | '/zz'
  id:
    | '__root__'
    | '/'
    | '/products/$productId'
    | '/czlan/'
    | '/events/'
    | '/meshcore/'
    | '/zz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  CzlanIndexRoute: typeof CzlanIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MeshcoreIndexRoute: typeof MeshcoreIndexRoute
  ZzIndexRoute: typeof ZzIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zz/': {
      id: '/zz/'
      path: '/zz'
      fullPath: '/zz/'
      preLoaderRoute: typeof ZzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meshcore/': {
      id: '/meshcore/'
      path: '/meshcore'
      fullPath: '/meshcore/'
      preLoaderRoute: typeof MeshcoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/czlan/': {
      id: '/czlan/'
      path: '/czlan'
      fullPath: '/czlan/'
      preLoaderRoute: typeof CzlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  CzlanIndexRoute: CzlanIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MeshcoreIndexRoute: MeshcoreIndexRoute,
  ZzIndexRoute: ZzIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
